<?xml version="1.0"?>
<robot name="omuni_bot"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="base_radius" value="0.5"/>
    <xacro:property name="base_height" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_zoff" value="0.015"/>

    <!-- 慣性計算マクロ -->
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <!-- 車輪マクロ -->
    <xacro:macro name="wheel" params="prefix x y r">
        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x} ${y} -${wheel_zoff}" rpy="0 0 ${r}"/>
            <axis xyz="0 1 0"/>
        </joint>
        <link name="${prefix}_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
        </link>
        <gazebo>
            <plugin filename="gz-sim-joint-controller-system" name="gz::sim::systems::JointController">
                <joint_name>${prefix}_joint</joint_name>
                <initial_velocity>0.0</initial_velocity>
                <topic>${prefix}_v</topic>
            </plugin>
        </gazebo>
    </xacro:macro>

    <!-- Lidarマクロ-->
    <xacro:macro name="lidar" params="prefix x y z r">
        <!-- 固定ジョイントで取り付け -->
        <joint name="${prefix}_lidar_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_lidar_link"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 ${r}"/>
        </joint>

        <!-- LIDAR リンク -->
        <link name="${prefix}_lidar_link">
            <visual name="${prefix}_lidar_link_visual">
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.0508" length="0.03"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>

            <collision name="${prefix}_lidar_link_collision">
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.0508" length="0.03"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference = "${prefix}_lidar_link">
            <sensor name="${prefix}_lidar" type="gpu_lidar">
                <always_on>true</always_on>
                <visualize>true</visualize>
                <update_rate>10</update_rate>
                <topic>${prefix}_scan</topic>
                <gz_frame_id>${prefix}_lidar_link</gz_frame_id>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>90</samples>
                            <resolution>1.000000</resolution>
                            <min_angle>${-pi/2.0-0.3}</min_angle>
                            <max_angle>${pi/2.0+0.3}</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.3</min>
                        <max>10.0</max>
                        <resolution>0.015000</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </ray>
            </sensor>
        </gazebo>
    </xacro:macro>

    <!-- ベースリンク -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 0.5 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="5.0" r="${base_radius}" h="${base_height}"/>
    </link>

    <!-- base_footprint -->
    <link name="base_footprint">
        <xacro:cylinder_inertia m="1.0" r="${base_radius}" h="${base_height}"/>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <!-- 車輪-->
    <xacro:wheel prefix="whl_lf" x="${1.4142/2.0*base_radius}" y="${1.4142/2.0*base_radius}" r="${3.0*pi/4.0}" />
    <xacro:wheel prefix="whl_rf" x="${1.4142/2.0*base_radius}" y="-${1.4142/2.0*base_radius}" r="${1.0*pi/4.0}"/>
    <xacro:wheel prefix="whl_rb" x="-${1.4142/2.0*base_radius}" y="-${1.4142/2.0*base_radius}" r="-${1.0*pi/4.0}"/>
    <xacro:wheel prefix="whl_lb" x="-${1.4142/2.0*base_radius}" y="${1.4142/2.0*base_radius}" r="-${3.0*pi/4.0}"/>

    <!-- Lidar-->
    <xacro:lidar prefix="left" x="${1.4142/2.0*(base_radius+0.05)}" y="${1.4142/2.0*(base_radius+0.05)}" z="0.0" r="${pi/4.0 * 1.0}"/>
    <xacro:lidar prefix="right" x="-${1.4142/2.0*(base_radius+0.05)}" y="-${1.4142/2.0*(base_radius+0.05)}" z="0.0" r="${pi/4.0 * 5.0}"/>

</robot>